# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'abandoned_object_detect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AbandonedObjectDetect(object):
    def setupUi(self, AbandonedObjectDetect):
        AbandonedObjectDetect.setObjectName("AbandonedObjectDetect")
        AbandonedObjectDetect.resize(1280, 824)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        AbandonedObjectDetect.setFont(font)
        icon = QtGui.QIcon.fromTheme("window_icon")
        AbandonedObjectDetect.setWindowIcon(icon)
        AbandonedObjectDetect.setStyleSheet("font: 10pt \"华文琥珀\";\n"
"                QPushButton\n"
"                {text-align : center;\n"
"                background-color : white;\n"
"                font: bold;\n"
"                border-color: ;\n"
"                color: rgb(255, 255, 255);\n"
"                border-width: 5px;\n"
"                border-radius: 10px;\n"
"                padding: 6px;\n"
"                height : 14px;\n"
"                border-style: outset;\n"
"                font : 14px;}\n"
"                QPushButton:pressed\n"
"                {text-align : center;\n"
"                background-color : light gray;\n"
"                font: bold;\n"
"                border-color: gray;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                padding: 6px;\n"
"                height : 14px;\n"
"                border-style: outset;\n"
"                font : 14px;}\n"
"            ")
        self.centralwidget = QtWidgets.QWidget(AbandonedObjectDetect)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_7.addWidget(self.tabWidget)
        AbandonedObjectDetect.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AbandonedObjectDetect)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 19))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        AbandonedObjectDetect.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AbandonedObjectDetect)
        self.statusbar.setObjectName("statusbar")
        AbandonedObjectDetect.setStatusBar(self.statusbar)
        self.abandoned_object_detect = QtWidgets.QAction(AbandonedObjectDetect)
        self.abandoned_object_detect.setObjectName("abandoned_object_detect")
        self.about_us = QtWidgets.QAction(AbandonedObjectDetect)
        self.about_us.setObjectName("about_us")
        self.menu.addSeparator()
        self.menu_3.addAction(self.about_us)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(AbandonedObjectDetect)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(AbandonedObjectDetect)

    def retranslateUi(self, AbandonedObjectDetect):
        _translate = QtCore.QCoreApplication.translate
        AbandonedObjectDetect.setWindowTitle(_translate("AbandonedObjectDetect", "智慧教室"))
        self.menu.setTitle(_translate("AbandonedObjectDetect", "设置"))
        self.menu_3.setTitle(_translate("AbandonedObjectDetect", "帮助"))
        self.abandoned_object_detect.setText(_translate("AbandonedObjectDetect", "遗留物检测"))
        self.about_us.setText(_translate("AbandonedObjectDetect", "关于"))
