# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capture_item_component.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CaptureItem(object):
    def setupUi(self, CaptureItem):
        CaptureItem.setObjectName("CaptureItem")
        CaptureItem.resize(200, 193)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(7)
        CaptureItem.setFont(font)
        CaptureItem.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(CaptureItem)
        self.verticalLayout.setObjectName("verticalLayout")
        self.capture_img = QtWidgets.QLabel(CaptureItem)
        self.capture_img.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.capture_img.setText("")
        self.capture_img.setObjectName("capture_img")
        self.verticalLayout.addWidget(self.capture_img)
        self.capture_time = QtWidgets.QLabel(CaptureItem)
        self.capture_time.setAlignment(QtCore.Qt.AlignCenter)
        self.capture_time.setObjectName("capture_time")
        self.verticalLayout.addWidget(self.capture_time)
        self.verticalLayout.setStretch(0, 8)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(CaptureItem)
        QtCore.QMetaObject.connectSlotsByName(CaptureItem)

    def retranslateUi(self, CaptureItem):
        _translate = QtCore.QCoreApplication.translate
        CaptureItem.setWindowTitle(_translate("CaptureItem", "real_time_catch"))
        self.capture_time.setText(_translate("CaptureItem", "00:00:00"))
