# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_component.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(468, 342)
        self.login_button = QtWidgets.QPushButton(login)
        self.login_button.setGeometry(QtCore.QRect(75, 250, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.label = QtWidgets.QLabel(login)
        self.label.setGeometry(QtCore.QRect(100, 116, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(login)
        self.label_2.setGeometry(QtCore.QRect(100, 165, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.login_cancel_button = QtWidgets.QPushButton(login)
        self.login_cancel_button.setGeometry(QtCore.QRect(314, 250, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.login_cancel_button.setFont(font)
        self.login_cancel_button.setObjectName("login_cancel_button")
        self.username_text = QtWidgets.QTextEdit(login)
        self.username_text.setGeometry(QtCore.QRect(190, 113, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.username_text.setFont(font)
        self.username_text.setObjectName("username_text")
        self.password_text = QtWidgets.QTextEdit(login)
        self.password_text.setGeometry(QtCore.QRect(190, 170, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.password_text.setFont(font)
        self.password_text.setObjectName("password_text")
        self.login_warn = QtWidgets.QLabel(login)
        self.login_warn.setGeometry(QtCore.QRect(160, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.login_warn.setFont(font)
        self.login_warn.setStyleSheet("color:red")
        self.login_warn.setObjectName("login_warn")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "登录"))
        self.login_button.setText(_translate("login", "登录"))
        self.label.setText(_translate("login", "用户名:"))
        self.label_2.setText(_translate("login", "密   码:"))
        self.login_cancel_button.setText(_translate("login", "取消"))
        self.login_warn.setText(_translate("login", "请输入用户名和密码"))
